package com.syncrobotic.webrtc.signaling

import io.ktor.client.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*

/**
 * WHEP (WebRTC-HTTP Egress Protocol) client for receiving streams from streaming.
 * 
 * WHEP is a simple HTTP-based signaling protocol for WebRTC:
 * 1. Client sends SDP offer via HTTP POST
 * 2. Server responds with SDP answer
 * 3. ICE candidates are exchanged via PATCH requests (optional)
 * 
 * @see https://datatracker.ietf.org/doc/draft-ietf-wish-whep/
 */
@Deprecated(
    message = "Use WhepSignalingAdapter instead. Will be removed in v3.0.",
    replaceWith = ReplaceWith("WhepSignalingAdapter(url, auth, httpClient)", "com.syncrobotic.webrtc.signaling.WhepSignalingAdapter")
)
class WhepSignaling(
    private val httpClient: HttpClient
) {
    /**
     * Result of a WHEP session initiation.
     */
    data class SessionResult(
        /** SDP answer from the server */
        val sdpAnswer: String,
        /** Session resource URL for ICE trickling and teardown */
        val resourceUrl: String?,
        /** ETag for the session (used in PATCH requests) */
        val etag: String?,
        /** Link headers for ICE servers */
        val iceServers: List<String>
    )

    /**
     * Initiate a WHEP session by sending an SDP offer.
     * 
     * @param whepUrl The WHEP endpoint URL (e.g., "http://10.42.0.98:8889/raw")
     * @param sdpOffer The SDP offer generated by the local PeerConnection
     * @return SessionResult containing the SDP answer and session info
     * @throws WhepException if the request fails
     */
    suspend fun sendOffer(whepUrl: String, sdpOffer: String): SessionResult {
        try {
            val response = httpClient.post(whepUrl) {
                contentType(ContentType("application", "sdp"))
                setBody(sdpOffer)
            }

            if (response.status != HttpStatusCode.Created && response.status != HttpStatusCode.OK) {
                throw WhepException(
                    "WHEP offer failed with status ${response.status.value}: ${response.bodyAsText()}"
                )
            }

            val sdpAnswer = response.bodyAsText()
            val locationHeader = response.headers[HttpHeaders.Location]
            // Resolve relative URL to absolute URL using the request URL as base
            val resourceUrl = locationHeader?.let { loc ->
                if (loc.startsWith("http://") || loc.startsWith("https://")) {
                    loc // Already absolute
                } else {
                    // Build absolute URL from base URL and relative path
                    val baseUrl = Url(whepUrl)
                    URLBuilder(baseUrl).apply {
                        encodedPath = loc
                    }.buildString()
                }
            }
            val etag = response.headers[HttpHeaders.ETag]
            
            // Parse Link headers for ICE servers
            val iceServers = response.headers.getAll(HttpHeaders.Link)
                ?.filter { it.contains("rel=\"ice-server\"") }
                ?: emptyList()

            return SessionResult(
                sdpAnswer = sdpAnswer,
                resourceUrl = resourceUrl,
                etag = etag,
                iceServers = iceServers
            )
        } catch (e: WhepException) {
            throw e
        } catch (e: Exception) {
            throw WhepException("Failed to send WHEP offer: ${e.message}", e)
        }
    }

    /**
     * Send an ICE candidate via PATCH request (trickle ICE).
     */
    suspend fun sendIceCandidate(
        resourceUrl: String,
        candidate: String,
        etag: String? = null,
        iceUfrag: String? = null,
        icePwd: String? = null,
        mid: String? = null
    ) {
        try {
            val sdpLines = mutableListOf<String>()
            if (!iceUfrag.isNullOrBlank()) {
                sdpLines.add("a=ice-ufrag:$iceUfrag")
            }
            if (!icePwd.isNullOrBlank()) {
                sdpLines.add("a=ice-pwd:$icePwd")
            }
            if (!mid.isNullOrBlank()) {
                sdpLines.add("a=mid:$mid")
            }
            sdpLines.add(candidate.trimEnd())
            val sdpFragment = sdpLines.joinToString("\r\n", postfix = "\r\n")

            val response = httpClient.patch(resourceUrl) {
                contentType(ContentType("application", "trickle-ice-sdpfrag"))
                etag?.let { header(HttpHeaders.IfMatch, it) }
                setBody(sdpFragment)
            }

            if (response.status != HttpStatusCode.NoContent && 
                response.status != HttpStatusCode.OK) {
                val responseBody = response.bodyAsText()
                throw WhepException(
                    "Failed to send ICE candidate: ${response.status.value}: $responseBody"
                )
            }
        } catch (e: WhepException) {
            throw e
        } catch (e: Exception) {
            throw WhepException("Failed to send ICE candidate: ${e.message}", e)
        }
    }

    /**
     * Terminate the WHEP session.
     */
    suspend fun terminateSession(resourceUrl: String) {
        try {
            httpClient.delete(resourceUrl)
        } catch (e: Exception) {
            // Ignore errors on teardown
        }
    }
}

/**
 * Exception thrown when WHEP signaling fails.
 */
class WhepException(
    message: String,
    cause: Throwable? = null
) : Exception(message, cause)

/**
 * WHIP (WebRTC-HTTP Ingress Protocol) client for publishing streams to streaming.
 * 
 * WHIP is a simple HTTP-based signaling protocol for WebRTC ingress (sending):
 * 1. Client sends SDP offer via HTTP POST
 * 2. Server responds with SDP answer
 * 3. ICE candidates are exchanged via PATCH requests (trickle ICE)
 * 
 * @see https://datatracker.ietf.org/doc/draft-ietf-wish-whip/
 */
@Deprecated(
    message = "Use WhipSignalingAdapter instead. Will be removed in v3.0.",
    replaceWith = ReplaceWith("WhipSignalingAdapter(url, auth, httpClient)", "com.syncrobotic.webrtc.signaling.WhipSignalingAdapter")
)
class WhipSignaling(
    private val httpClient: HttpClient
) {
    /**
     * Result of a WHIP session initiation.
     */
    data class SessionResult(
        /** SDP answer from the server */
        val sdpAnswer: String,
        /** Session resource URL for ICE trickling and teardown */
        val resourceUrl: String?,
        /** ETag for the session (used in PATCH requests) */
        val etag: String?,
        /** Link headers for ICE servers */
        val iceServers: List<String> = emptyList()
    )

    /**
     * Initiate a WHIP session by sending an SDP offer.
     * 
     * @param whipUrl The WHIP endpoint URL (e.g., "http://10.42.0.98:8889/stream/whip")
     * @param sdpOffer The SDP offer generated by the local PeerConnection
     * @return SessionResult containing the SDP answer and session info
     * @throws WhipException if the request fails
     */
    suspend fun sendOffer(whipUrl: String, sdpOffer: String): SessionResult {
        try {
            val response = httpClient.post(whipUrl) {
                contentType(ContentType("application", "sdp"))
                setBody(sdpOffer)
            }

            if (response.status != HttpStatusCode.Created && response.status != HttpStatusCode.OK) {
                val errorBody = response.bodyAsText()
                throw WhipException(
                    code = WhipErrorCode.OFFER_REJECTED,
                    message = "WHIP offer failed with status ${response.status.value}: $errorBody"
                )
            }

            val sdpAnswer = response.bodyAsText()
            val locationHeader = response.headers[HttpHeaders.Location]
            // Resolve relative URL to absolute URL using the request URL as base
            val resourceUrl = locationHeader?.let { loc ->
                if (loc.startsWith("http://") || loc.startsWith("https://")) {
                    loc // Already absolute
                } else {
                    // Build absolute URL from base URL and relative path
                    val baseUrl = Url(whipUrl)
                    URLBuilder(baseUrl).apply {
                        encodedPath = loc
                    }.buildString()
                }
            }
            val etag = response.headers[HttpHeaders.ETag]
            
            // Parse Link headers for ICE servers
            val iceServers = response.headers.getAll(HttpHeaders.Link)
                ?.filter { it.contains("rel=\"ice-server\"") }
                ?: emptyList()

            return SessionResult(
                sdpAnswer = sdpAnswer,
                resourceUrl = resourceUrl,
                etag = etag,
                iceServers = iceServers
            )
        } catch (e: WhipException) {
            throw e
        } catch (e: Exception) {
            throw WhipException(
                code = WhipErrorCode.NETWORK_ERROR,
                message = "Failed to send WHIP offer: ${e.message}",
                cause = e
            )
        }
    }

    /**
     * Send an ICE candidate via PATCH request (trickle ICE).
     * 
     * @param resourceUrl The session resource URL from sendOffer result
     * @param candidate The ICE candidate string (a=candidate:...)
     * @param etag Optional ETag for conditional update
     * @param iceUfrag ICE username fragment
     * @param icePwd ICE password
     * @param mid Media ID (e.g., "0", "1", "audio", "video")
     */
    suspend fun sendIceCandidate(
        resourceUrl: String,
        candidate: String,
        etag: String? = null,
        iceUfrag: String? = null,
        icePwd: String? = null,
        mid: String? = null
    ) {
        try {
            val sdpLines = mutableListOf<String>()
            if (!iceUfrag.isNullOrBlank()) {
                sdpLines.add("a=ice-ufrag:$iceUfrag")
            }
            if (!icePwd.isNullOrBlank()) {
                sdpLines.add("a=ice-pwd:$icePwd")
            }
            if (!mid.isNullOrBlank()) {
                sdpLines.add("a=mid:$mid")
            }
            sdpLines.add(candidate.trimEnd())
            val sdpFragment = sdpLines.joinToString("\r\n", postfix = "\r\n")

            val response = httpClient.patch(resourceUrl) {
                contentType(ContentType("application", "trickle-ice-sdpfrag"))
                etag?.let { header(HttpHeaders.IfMatch, it) }
                setBody(sdpFragment)
            }

            if (response.status != HttpStatusCode.NoContent && 
                response.status != HttpStatusCode.OK) {
                val responseBody = response.bodyAsText()
                throw WhipException(
                    code = WhipErrorCode.ICE_CANDIDATE_FAILED,
                    message = "Failed to send ICE candidate: ${response.status.value}: $responseBody"
                )
            }
        } catch (e: WhipException) {
            throw e
        } catch (e: Exception) {
            throw WhipException(
                code = WhipErrorCode.NETWORK_ERROR,
                message = "Failed to send ICE candidate: ${e.message}",
                cause = e
            )
        }
    }

    /**
     * Terminate the WHIP session.
     * 
     * @param resourceUrl The session resource URL from sendOffer result
     */
    suspend fun terminateSession(resourceUrl: String) {
        try {
            httpClient.delete(resourceUrl)
        } catch (e: Exception) {
            // Ignore errors on teardown
        }
    }
}

/**
 * Error codes for WHIP signaling failures.
 */
enum class WhipErrorCode {
    /** Network connectivity issue */
    NETWORK_ERROR,
    /** Server rejected the SDP offer */
    OFFER_REJECTED,
    /** Failed to send ICE candidate */
    ICE_CANDIDATE_FAILED,
    /** Session terminated unexpectedly */
    SESSION_TERMINATED,
    /** Unknown error */
    UNKNOWN
}

/**
 * Exception thrown when WHIP signaling fails.
 * 
 * @param code Error code indicating the type of failure
 * @param message Human-readable error message
 * @param cause Underlying exception if any
 */
class WhipException(
    val code: WhipErrorCode = WhipErrorCode.UNKNOWN,
    message: String,
    cause: Throwable? = null
) : Exception(message, cause)
